// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: Client2GateProtocols.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
using CommonRpc.RpcBase;
using FlatSharp.Attributes;
using MessagePack;
using System;
using System.ComponentModel;

namespace Protocol.Param
{


}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
