// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: World2LogicProtocols.proto

using CommonRpc.RpcBase;
using FlatSharp.Attributes;
using MessagePack;
using ProtoBuf;
using Protocol;

namespace Protocol.Param
{

    [MessagePackObject]
    public class WorldLoginData
    {
        [Key(1)]
        public string Token { get; set; }
    }

    [MessagePackObject]
    public class WorldLoginRet :RpcResult<WorldLoginRet>
    {
        [Key(2)]
        public uint GlobalSessionID { get; set; }

        [Key(3)]
        public int PlayerID { get; set; }

        [Key(4)]
        public EnumResultType Result { get; set; } = EnumResultType.Fail;
    }


}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
